version: '3.8'

services:
  onedrive-to-r2-browser:
    build:
      context: .
      dockerfile: Dockerfile.browser
    environment:
      # R2 Configuration
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      
      # Browser Configuration
      - DISPLAY=:99
      - CHROME_PATH=/usr/bin/google-chrome-stable
      
    # Resource limits for browser automation
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '1.0'
          memory: 2G
    
    # Security options for browser
    security_opt:
      - seccomp:unconfined
    
    # Shared memory size for browser
    shm_size: 2gb
    
    volumes:
      - .env:/app/.env:ro
      - ./links.txt:/app/links.txt:ro
    
    # Example usage: process single link
    # docker-compose -f docker-compose.browser.yml run --rm onedrive-to-r2-browser "https://1drv.ms/..."
    
    # Example usage: process file
    # docker-compose -f docker-compose.browser.yml run --rm onedrive-to-r2-browser --file links.txt 